GET http://localhost:3000/usuarios

###

POST http://localhost:3000/usuarios
Content-Type: application/json

{
    "usuario": "carlos2",
    "ativo": true
}

###

GET http://localhost:3000/usuarios/5

###

DELETE http://localhost:3000/usuarios/1